%{
/* Inmanta grammar — generated by misc/ply_to_yacc.py */
%}

%token INT FLOAT ID CID SEP STRING MLS CMP_OP REGEX REL PEQ RSTRING FSTRING PLUS_OP MINUS_OP DIVISION_OP DOUBLE_STAR MOD
%token AND          /* and */
%token AS           /* as */
%token DEFINED      /* defined */
%token DICT         /* dict */
%token ELIF         /* elif */
%token ELSE         /* else */
%token END          /* end */
%token ENTITY       /* entity */
%token EXTENDS      /* extends */
%token FALSE        /* false */
%token FOR          /* for */
%token IF           /* if */
%token IMPLEMENT    /* implement */
%token IMPLEMENTATION /* implementation */
%token IMPORT       /* import */
%token IN           /* in */
%token INDEX        /* index */
%token IS           /* is */
%token MATCHING     /* matching */
%token NOT          /* not */
%token NULL         /* null */
%token OR           /* or */
%token PARENTS      /* parents */
%token TRUE         /* true */
%token TYPEDEF      /* typedef */
%token UNDEF        /* undef */
%token USING        /* using */
%token WHEN         /* when */

%nonassoc LOW
%nonassoc MATCHING
%nonassoc REGEX
%right ','
%nonassoc ':'
%nonassoc '?'
%left OR
%left AND
%left CMP_OP
%left PLUS_OP MINUS_OP
%left '*' DIVISION_OP MOD
%left DOUBLE_STAR
%nonassoc NOT
%left IN
%left CID ID
%left '(' '['
%left MLS

%%

main:
          head body
    ;

empty:
          /* empty */ %prec LOW
    ;

head:
          empty
        | MLS
    ;

body:
          top_stmt body
        | empty
    ;

top_stmt:
          entity_def
        | implement_def
        | implementation_def
        | relation
        | statement
        | typedef
        | index
        | import
    ;

import:
          IMPORT ns_ref
        | IMPORT ns_ref AS ID
    ;

statement:
          assign
        | for
        | if
        | expression empty
    ;

stmt_list:
          statement stmt_list
        | empty
    ;

assign:
          var_ref '=' operand
        | var_ref PEQ operand
    ;

for:
          FOR ID IN operand ':' block
    ;

if:
          IF if_body END
    ;

if_body:
          expression ':' stmt_list if_next
    ;

if_next:
          empty
        | ELSE ':' stmt_list
        | ELIF if_body
    ;

entity_def:
          ENTITY CID ':' entity_body_outer
        | ENTITY ID ':' entity_body_outer
        | ENTITY CID EXTENDS class_ref_list ':' entity_body_outer
        | ENTITY ID EXTENDS class_ref_list ':' entity_body_outer
    ;

entity_body_outer:
          MLS entity_body END
        | entity_body END
        | END
        | MLS END
    ;

entity_body:
          entity_body attr
        | attr
    ;

attr_base_type:
          ns_ref
    ;

attr_type_multi:
          attr_base_type '[' ']'
    ;

attr_type_opt:
          attr_type_multi '?'
        | attr_base_type '?'
    ;

attr_type:
          attr_type_opt
        | attr_type_multi
        | attr_base_type
    ;

attr:
          attr_type CID empty
        | attr_type CID '=' constant
        | attr_type CID '=' constant_list
        | attr_type CID '=' UNDEF
        | attr_type ID
        | attr_type ID '=' constant
        | attr_type ID '=' constant_list
        | attr_type ID '=' UNDEF
        | DICT empty CID empty
        | DICT empty CID '=' map_def
        | DICT empty CID '=' NULL
        | DICT '?' CID empty
        | DICT '?' CID '=' map_def
        | DICT '?' CID '=' NULL
        | DICT ID
        | DICT ID '=' map_def
        | DICT ID '=' NULL
        | DICT '?' ID
        | DICT '?' ID '=' map_def
        | DICT '?' ID '=' NULL
    ;

implement_ns_list:
          ns_ref
        | PARENTS
        | implement_ns_list ',' implement_ns_list
    ;

implement_def:
          IMPLEMENT class_ref USING implement_ns_list empty
        | IMPLEMENT class_ref USING implement_ns_list MLS
        | IMPLEMENT class_ref USING implement_ns_list WHEN expression empty
        | IMPLEMENT class_ref USING implement_ns_list WHEN expression MLS
    ;

implementation_def:
          IMPLEMENTATION ID FOR class_ref implementation
    ;

implementation:
          implementation_head block
    ;

implementation_head:
          ':'
        | ':' MLS
    ;

block:
          stmt_list END
    ;

relation:
          relation_def MLS
        | relation_def empty
    ;

relation_def:
          class_ref '.' ID multi REL class_ref '.' ID multi
        | class_ref '.' ID multi REL class_ref
        | class_ref '.' ID multi operand_list class_ref '.' ID multi
        | class_ref '.' ID multi operand_list class_ref
    ;

multi:
          '[' INT ']'
        | '[' INT ':' ']'
        | '[' INT ':' INT ']'
        | '[' ':' INT ']'
    ;

typedef:
          typedef_inner empty
        | typedef_inner MLS
    ;

typedef_inner:
          TYPEDEF ID AS ns_ref MATCHING expression
        | TYPEDEF ID AS ns_ref REGEX
        | TYPEDEF CID AS constructor
    ;

index:
          INDEX class_ref '(' id_list ')'
    ;

expression:
          boolean_expression
        | constant
        | function_call
        | var_ref empty
        | constructor
        | list_def
        | list_comprehension
        | map_def
        | map_lookup empty
        | index_lookup
        | conditional_expression
        | arithmetic_expression
        | '(' expression ')'
    ;

boolean_expression:
          expression CMP_OP expression
        | expression IN expression
        | expression AND expression
        | expression OR expression
        | expression NOT IN expression
        | NOT expression
        | var_ref '.' ID IS DEFINED
        | ID IS DEFINED
        | map_lookup IS DEFINED
    ;

arithmetic_expression:
          expression PLUS_OP expression
        | expression MINUS_OP expression
        | expression DIVISION_OP expression
        | expression '*' expression
        | expression MOD expression
        | expression DOUBLE_STAR expression
    ;

operand:
          expression empty
    ;

map_lookup:
          attr_ref '[' operand ']'
        | var_ref '[' operand ']'
        | map_lookup '[' operand ']'
    ;

constructor:
          class_ref '(' param_list ')'
    ;

function_call:
          ns_ref '(' function_param_list ')'
        | attr_ref '(' function_param_list ')'
    ;

list_def:
          '[' operand_list ']'
    ;

list_comprehension:
          '[' expression list_comprehension_for list_comprehension_guard ']'
    ;

list_comprehension_for_empty:
          empty
    ;

list_comprehension_for:
          FOR ID IN expression list_comprehension_for_empty
        | FOR ID IN expression list_comprehension_for
    ;

list_comprehension_guard:
          empty
        | IF expression list_comprehension_guard
    ;

dict_key:
          RSTRING
        | STRING
    ;

pair_list:
          dict_key ':' operand ',' pair_list
        | dict_key ':' operand empty pair_list_empty
        | pair_list_empty
    ;

pair_list_empty:
          empty
    ;

map_def:
          '{' pair_list '}'
    ;

index_lookup:
          class_ref '[' param_list ']'
        | attr_ref '[' param_list ']'
    ;

conditional_expression:
          expression '?' expression ':' expression
    ;

constant:
          INT
        | FLOAT
        | NULL
        | REGEX
        | TRUE
        | FALSE
        | STRING
        | FSTRING
        | RSTRING
        | MLS
    ;

constant_list:
          '[' constants ']'
    ;

constants:
          constant
        | /* empty */
        | constant ',' constants
    ;

wrapped_kwargs:
          DOUBLE_STAR operand
    ;

param_list_element:
          ID '=' operand
        | wrapped_kwargs
    ;

param_list:
          param_list_empty
        | param_list_element empty param_list_empty
        | param_list_element ',' param_list
    ;

param_list_empty:
          empty
    ;

function_param_list_element:
          param_list_element
        | operand
    ;

function_param_list:
          function_param_list_empty
        | function_param_list_element empty function_param_list_empty
        | function_param_list_element ',' function_param_list
    ;

function_param_list_empty:
          empty
    ;

operand_list:
          operand ',' operand_list
        | operand
        | empty
    ;

var_ref:
          attr_ref empty
        | ns_ref empty
    ;

attr_ref:
          var_ref '.' ID
    ;

class_ref:
          CID
        | ns_ref SEP CID
        | var_ref '.' CID
    ;

class_ref_list:
          class_ref ',' class_ref_list
        | var_ref ',' class_ref_list
        | class_ref
        | var_ref
    ;

ns_ref:
          ns_ref SEP ID
        | ID
    ;

id_list:
          ID ',' id_list
        | ID
    ;

%%
